Imported Upstream version 0.22

diff --git a/data/Makefile.in b/data/Makefile.in
--- a/data/Makefile.in
+++ b/data/Makefile.in
@@ -236,6 +236,7 @@ ECHO_T = @ECHO_T@
 EGREP = @EGREP@
 EXEEXT = @EXEEXT@
 FGREP = @FGREP@
+GIT = @GIT@
 GLIB_236_CFLAGS = @GLIB_236_CFLAGS@
 GLIB_236_LIBS = @GLIB_236_LIBS@
 GLIB_CFLAGS = @GLIB_CFLAGS@
@@ -341,9 +342,11 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 libwacomtabletdir = $(datadir)/libwacom
-dist_libwacomtablet_DATA = $(shell find $(top_srcdir)/data -name "*.tablet" -printf "%P\n")
+tablet_files = $(shell find $(top_srcdir)/data -name "*.tablet" -printf "%P\n")
+dist_libwacomtablet_DATA = $(tablet_files)
 libwacomstylusdir = $(datadir)/libwacom
-dist_libwacomstylus_DATA = $(shell find $(top_srcdir)/data -name "*.stylus" -printf "%P\n")
+stylus_files = $(shell find $(top_srcdir)/data -name "*.stylus" -printf "%P\n")
+dist_libwacomstylus_DATA = $(stylus_files)
 EXTRA_DIST = wacom.example
 SUBDIRS = layouts
 all: all-recursive
@@ -708,6 +711,23 @@ uninstall-am: uninstall-dist_libwacomstylusDATA \
 
 .PRECIOUS: Makefile
 
+
+check:
+	@for file in $(tablet_files); do \
+		svg=`$(GREP) 'Layout=' "$(top_srcdir)/data/$$file" | $(SED) -e "s/Layout=//"`; \
+		test -z "$$svg" || \
+		test -e "$(top_srcdir)/data/layouts/$$svg" || ( \
+			echo "ERROR: File $$file references nonexistent $$svg" && test); \
+		rc="$$(($$rc + $$?))"; \
+	done && test 0 -eq $$rc;
+	@(export GIT_DIR="$(top_srcdir)/.git"; \
+	 if $(GIT) ls-files >& /dev/null; then \
+		for file in $(tablet_files) $(stylus_files); do \
+			$(GIT) ls-files --error-unmatch "data/$$file" &> /dev/null || ( \
+			echo "ERROR: File $$file is not in git" && test); \
+		rc="$$(($$rc + $$?))"; \
+		done && test 0 -eq $$rc; \
+	fi)
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
diff --git a/data/layouts/Makefile.in b/data/layouts/Makefile.in
--- a/data/layouts/Makefile.in
+++ b/data/layouts/Makefile.in
@@ -175,6 +175,7 @@ ECHO_T = @ECHO_T@
 EGREP = @EGREP@
 EXEEXT = @EXEEXT@
 FGREP = @FGREP@
+GIT = @GIT@
 GLIB_236_CFLAGS = @GLIB_236_CFLAGS@
 GLIB_236_LIBS = @GLIB_236_LIBS@
 GLIB_CFLAGS = @GLIB_CFLAGS@
@@ -280,7 +281,8 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 libwacomlayoutsdir = $(datadir)/libwacom/layouts
-dist_libwacomlayouts_DATA = $(shell find $(top_srcdir)/data/layouts -name "*.svg" -printf "%P\n")
+layouts = $(shell find $(top_srcdir)/data/layouts -name "*.svg" -printf "%P\n")
+dist_libwacomlayouts_DATA = $(layouts)
 EXTRA_DIST = README
 all: all-am
 
@@ -498,6 +500,21 @@ uninstall-am: uninstall-dist_libwacomlayoutsDATA
 
 .PRECIOUS: Makefile
 
+
+check:
+	@for file in $(layouts); do \
+		$(GREP) -q "$$file" $(top_srcdir)/data/*.tablet || (\
+			echo "ERROR: Layout $$file is not referenced" && test); \
+		rc="$$(($$rc + $$?))"; \
+	done && test 0 -eq $$rc;
+	@(export GIT_DIR="$(top_srcdir)/.git"; \
+	if $(GIT) ls-files >& /dev/null; then \
+		for file in $(layouts); do \
+			$(GIT) ls-files --error-unmatch "data/layouts/$$file" &> /dev/null || ( \
+			echo "ERROR: File $$file is not in git" && test); \
+		rc="$$(($$rc + $$?))"; \
+		done && test 0 -eq $$rc; \
+	fi)
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
